#!/bin/sh
wrapdocker
docker -d &
mkdir /tmp/build
echo "PACKAGES=$@"
pacman -b /tmp/build -r /tmp/build -Syddu --noconfirm $@
cd /tmp/build
tar -cf /build/rootfs.tar .
cd /build
docker build -t bb .
docker save bb > /output/bb.tar
